<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFzo9x1w\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFzo9x1w/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFzo9x1w.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFzo9x1w\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerFzo9x1w\appTestDebugProjectContainer([
    'container.build_hash' => 'Fzo9x1w',
    'container.build_id' => '9ef3081d',
    'container.build_time' => 1566546022,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFzo9x1w');
