<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKgglbzd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKgglbzd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKgglbzd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKgglbzd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKgglbzd\appDevDebugProjectContainer([
    'container.build_hash' => 'Kgglbzd',
    'container.build_id' => '0cbb7b76',
    'container.build_time' => 1566545535,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKgglbzd');
