<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pokemon extends \AppBundle\Entity\Pokemon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'hp', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'power', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'defense', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'speed', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'attacks', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'types'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'hp', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'power', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'defense', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'speed', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'attacks', '' . "\0" . 'AppBundle\\Entity\\Pokemon' . "\0" . 'types'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pokemon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setHp($hp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHp', [$hp]);

        return parent::setHp($hp);
    }

    /**
     * {@inheritDoc}
     */
    public function getHp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHp', []);

        return parent::getHp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPower($power)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPower', [$power]);

        return parent::setPower($power);
    }

    /**
     * {@inheritDoc}
     */
    public function getPower()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPower', []);

        return parent::getPower();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefense($defense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefense', [$defense]);

        return parent::setDefense($defense);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefense', []);

        return parent::getDefense();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeed($speed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeed', [$speed]);

        return parent::setSpeed($speed);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeed', []);

        return parent::getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    public function addType(\AppBundle\Entity\Type $type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addType', [$type]);

        return parent::addType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function removeType(\AppBundle\Entity\Type $type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeType', [$type]);

        return parent::removeType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypes', []);

        return parent::getTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttack(\AppBundle\Entity\Attack $attack)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttack', [$attack]);

        return parent::addAttack($attack);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttack(\AppBundle\Entity\Attack $attack)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttack', [$attack]);

        return parent::removeAttack($attack);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttacks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttacks', []);

        return parent::getAttacks();
    }

    /**
     * {@inheritDoc}
     */
    public function getRandomAttack()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRandomAttack', []);

        return parent::getRandomAttack();
    }

}
