<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fight extends \AppBundle\Entity\Fight implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'winner', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'pokemon2', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'user1', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'pokemon1', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'user2', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'turns'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'winner', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'pokemon2', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'user1', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'pokemon1', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'user2', '' . "\0" . 'AppBundle\\Entity\\Fight' . "\0" . 'turns'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fight $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setWinner($winner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWinner', [$winner]);

        return parent::setWinner($winner);
    }

    /**
     * {@inheritDoc}
     */
    public function getWinner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWinner', []);

        return parent::getWinner();
    }

    /**
     * {@inheritDoc}
     */
    public function setPokemon2(\AppBundle\Entity\Pokemon $pokemon2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPokemon2', [$pokemon2]);

        return parent::setPokemon2($pokemon2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPokemon2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPokemon2', []);

        return parent::getPokemon2();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser1(\AppBundle\Entity\User $user1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser1', [$user1]);

        return parent::setUser1($user1);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser1', []);

        return parent::getUser1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPokemon1(\AppBundle\Entity\Pokemon $pokemon1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPokemon1', [$pokemon1]);

        return parent::setPokemon1($pokemon1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPokemon1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPokemon1', []);

        return parent::getPokemon1();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser2(\AppBundle\Entity\User $user2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser2', [$user2]);

        return parent::setUser2($user2);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser2', []);

        return parent::getUser2();
    }

    /**
     * {@inheritDoc}
     */
    public function isOver()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOver', []);

        return parent::isOver();
    }

    /**
     * {@inheritDoc}
     */
    public function addTurn(\AppBundle\Entity\FightTurn $turn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTurn', [$turn]);

        return parent::addTurn($turn);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTurn(\AppBundle\Entity\FightTurn $turn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTurn', [$turn]);

        return parent::removeTurn($turn);
    }

    /**
     * {@inheritDoc}
     */
    public function getTurns()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTurns', []);

        return parent::getTurns();
    }

    /**
     * {@inheritDoc}
     */
    public function getFastestPokemon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFastestPokemon', []);

        return parent::getFastestPokemon();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlowestPokemon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlowestPokemon', []);

        return parent::getSlowestPokemon();
    }

}
