<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FightTurn extends \AppBundle\Entity\FightTurn implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'pokemon1Hp', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'pokemon2Hp', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'attack2', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'fight', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'attack1'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'pokemon1Hp', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'pokemon2Hp', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'attack2', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'fight', '' . "\0" . 'AppBundle\\Entity\\FightTurn' . "\0" . 'attack1'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FightTurn $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPokemon1Hp($pokemon1Hp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPokemon1Hp', [$pokemon1Hp]);

        return parent::setPokemon1Hp($pokemon1Hp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPokemon1Hp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPokemon1Hp', []);

        return parent::getPokemon1Hp();
    }

    /**
     * {@inheritDoc}
     */
    public function setPokemon2Hp($pokemon2Hp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPokemon2Hp', [$pokemon2Hp]);

        return parent::setPokemon2Hp($pokemon2Hp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPokemon2Hp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPokemon2Hp', []);

        return parent::getPokemon2Hp();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttack2(\AppBundle\Entity\Attack $attack2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttack2', [$attack2]);

        return parent::setAttack2($attack2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttack2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttack2', []);

        return parent::getAttack2();
    }

    /**
     * {@inheritDoc}
     */
    public function setFight(\AppBundle\Entity\Fight $fight = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFight', [$fight]);

        return parent::setFight($fight);
    }

    /**
     * {@inheritDoc}
     */
    public function getFight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFight', []);

        return parent::getFight();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttack1(\AppBundle\Entity\Attack $attack1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttack1', [$attack1]);

        return parent::setAttack1($attack1);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttack1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttack1', []);

        return parent::getAttack1();
    }

}
